$HTMLBody .= '<!DOCTYPE html>'.NL;
$HTMLBody .= '<html>'.NL;
$HTMLBody .= '<head>'.NL;
$HTMLBody .= '<meta name="viewport" content="width=device-width, initial-scale=1">'.NL;
$HTMLBody .= '<link rel='stylesheet' type='text/css' href='styletest.css'>'.NL;
$HTMLBody .= '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">'.NL;
$HTMLBody .= '</head>'.NL;
$HTMLBody .= '<body>'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= '<div class="container" id="intranetContainer">'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= '<div class="header" id="intranetHeader">'.NL;
$HTMLBody .= '	<div class="logo">'.NL;
$HTMLBody .= '		<img src="logo.png" height="80px">'.NL;
$HTMLBody .= '	</div>'.NL;
$HTMLBody .= '	<div class="text">'.NL;
$HTMLBody .= '		<h2>INTRANET</h2>'.NL;
$HTMLBody .= '	</div>'.NL;
$HTMLBody .= '</div>'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= '<div class="navbar" id="intranetNavbar">'.NL;
$HTMLBody .= '  <a href="#home" class="active">Home</a>'.NL;
$HTMLBody .= '  <a href="#Ledenlijst">Ledenlijst</a>'.NL;
$HTMLBody .= '  <a href="#Roosters">Roosters</a>'.NL;
$HTMLBody .= '  <a href="#Links">Links</a>'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= '  <div class="navbar-right">'.NL;
$HTMLBody .= '	  <div class="dropdown" id="dropdownAccount">'.NL;
$HTMLBody .= '		<button class="dropbtn">Ingelogd als Tim Meijer'.NL;
$HTMLBody .= '		  <i class="fa fa-caret-down"></i>'.NL;
$HTMLBody .= '		</button>'.NL;
$HTMLBody .= '		<div class="dropdown-content">'.NL;
$HTMLBody .= '		  <a href="#">Link 1</a>'.NL;
$HTMLBody .= '		  <a href="#">Link 2</a>'.NL;
$HTMLBody .= '		  <a href="#">Link 3</a>'.NL;
$HTMLBody .= '		</div>'.NL;
$HTMLBody .= '	  </div>'.NL;
$HTMLBody .= '	  <a href="#logout" class="fa fa-sign-out"></a>'.NL;
$HTMLBody .= '	</div>'.NL;
$HTMLBody .= '  <a href="javascript:void(0);" style="font-size:15px;" class="icon" onclick="myFunction()">&#9776;</a>'.NL;
$HTMLBody .= '</div>'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= '<div style="padding-left:16px">'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <h2>This is a testline</h2>'.NL;
$HTMLBody .= '  <p>BLABLABLABLA</p>'.NL;
$HTMLBody .= '</div>'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= '<div class="footer" id="intranetFooter">'.NL;
$HTMLBody .= '	<img src="logo.png">'.NL;
$HTMLBody .= '	<p>Intranet Koningskerk Deventer - 2020</p>'.NL;
$HTMLBody .= '</div>'.NL;
$HTMLBody .= '</div>'.NL;
$HTMLBody .= '</body>'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= '<script>'.NL;
$HTMLBody .= ''.NL;
$HTMLBody .= 'function myFunction() {'.NL;
$HTMLBody .= '  var x = document.getElementById("intranetNavbar");'.NL;
$HTMLBody .= '  if (x.className === "navbar") {'.NL;
$HTMLBody .= '    x.className += " responsive";'.NL;
$HTMLBody .= '  } else {'.NL;
$HTMLBody .= '    x.className = "navbar";'.NL;
$HTMLBody .= '  }'.NL;
$HTMLBody .= '}'.NL;
$HTMLBody .= '</script>'.NL;
