<?php
unset($LaPostaHeader);
unset($LaPostaFooter);

#HEADER
$LaPostaHeader[] = '<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">';
$LaPostaHeader[] = '    <head>';
$LaPostaHeader[] = '        <!-- NAME: 1 COLUMN -->';
$LaPostaHeader[] = '        <!--[if gte mso 15]>';
$LaPostaHeader[] = '        <xml>';
$LaPostaHeader[] = '            <o:OfficeDocumentSettings>';
$LaPostaHeader[] = '            <o:AllowPNG/>';
$LaPostaHeader[] = '            <o:PixelsPerInch>96</o:PixelsPerInch>';
$LaPostaHeader[] = '            </o:OfficeDocumentSettings>';
$LaPostaHeader[] = '        </xml>';
$LaPostaHeader[] = '        <![endif]-->';
$LaPostaHeader[] = '        <meta charset="UTF-8">';
$LaPostaHeader[] = '        <meta http-equiv="X-UA-Compatible" content="IE=edge">';
$LaPostaHeader[] = '        <meta name="viewport" content="width=device-width, initial-scale=1">';
$LaPostaHeader[] = '        <title>Standaard LaPosta-template Koningskerk Deventer</title>';
$LaPostaHeader[] = '        ';
$LaPostaHeader[] = '    <style type="text/css">';
$LaPostaHeader[] = '		p{';
$LaPostaHeader[] = '			margin:10px 0;';
$LaPostaHeader[] = '			padding:0;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		table{';
$LaPostaHeader[] = '			border-collapse:collapse;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		h1,h2,h3,h4,h5,h6{';
$LaPostaHeader[] = '			display:block;';
$LaPostaHeader[] = '			margin:0;';
$LaPostaHeader[] = '			padding:0;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		img,a img{';
$LaPostaHeader[] = '			border:0;';
$LaPostaHeader[] = '			height:auto;';
$LaPostaHeader[] = '			outline:none;';
$LaPostaHeader[] = '			text-decoration:none;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		body,#bodyTable,#bodyCell{';
$LaPostaHeader[] = '			height:100%;';
$LaPostaHeader[] = '			margin:0;';
$LaPostaHeader[] = '			padding:0;';
$LaPostaHeader[] = '			width:100%;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.mcnPreviewText{';
$LaPostaHeader[] = '			display:none !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#outlook a{';
$LaPostaHeader[] = '			padding:0;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		img{';
$LaPostaHeader[] = '			-ms-interpolation-mode:bicubic;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		table{';
$LaPostaHeader[] = '			mso-table-lspace:0pt;';
$LaPostaHeader[] = '			mso-table-rspace:0pt;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.ReadMsgBody{';
$LaPostaHeader[] = '			width:100%;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.ExternalClass{';
$LaPostaHeader[] = '			width:100%;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		p,a,li,td,blockquote{';
$LaPostaHeader[] = '			mso-line-height-rule:exactly;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		a[href^=tel],a[href^=sms]{';
$LaPostaHeader[] = '			color:inherit;';
$LaPostaHeader[] = '			cursor:default;';
$LaPostaHeader[] = '			text-decoration:none;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		p,a,li,td,body,table,blockquote{';
$LaPostaHeader[] = '			-ms-text-size-adjust:100%;';
$LaPostaHeader[] = '			-webkit-text-size-adjust:100%;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.ExternalClass,.ExternalClass p,.ExternalClass td,.ExternalClass div,.ExternalClass span,.ExternalClass font{';
$LaPostaHeader[] = '			line-height:100%;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		a[x-apple-data-detectors]{';
$LaPostaHeader[] = '			color:inherit !important;';
$LaPostaHeader[] = '			text-decoration:none !important;';
$LaPostaHeader[] = '			font-size:inherit !important;';
$LaPostaHeader[] = '			font-family:inherit !important;';
$LaPostaHeader[] = '			font-weight:inherit !important;';
$LaPostaHeader[] = '			line-height:inherit !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#bodyCell{';
$LaPostaHeader[] = '			padding:10px;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.templateContainer{';
$LaPostaHeader[] = '			max-width:600px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		a.mcnButton{';
$LaPostaHeader[] = '			display:block;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.mcnImage,.mcnRetinaImage{';
$LaPostaHeader[] = '			vertical-align:bottom;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.mcnTextContent{';
$LaPostaHeader[] = '			word-break:break-word;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.mcnTextContent img{';
$LaPostaHeader[] = '			height:auto !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.mcnDividerBlock{';
$LaPostaHeader[] = '			table-layout:fixed !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		body,#bodyTable{';
$LaPostaHeader[] = '			background-color:#fafafa;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#bodyCell{';
$LaPostaHeader[] = '			border-top:0;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		.templateContainer{';
$LaPostaHeader[] = '			border:0;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		h1{';
$LaPostaHeader[] = '			color:#8c1974;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:26px;';
$LaPostaHeader[] = '			font-style:normal;';
$LaPostaHeader[] = '			font-weight:bold;';
$LaPostaHeader[] = '			line-height:125%;';
$LaPostaHeader[] = '			letter-spacing:normal;';
$LaPostaHeader[] = '			text-align:left;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		h2{';
$LaPostaHeader[] = '			color:#202020;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:22px;';
$LaPostaHeader[] = '			font-style:normal;';
$LaPostaHeader[] = '			font-weight:bold;';
$LaPostaHeader[] = '			line-height:125%;';
$LaPostaHeader[] = '			letter-spacing:normal;';
$LaPostaHeader[] = '			text-align:left;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		h3{';
$LaPostaHeader[] = '			color:#202020;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:20px;';
$LaPostaHeader[] = '			font-style:normal;';
$LaPostaHeader[] = '			font-weight:bold;';
$LaPostaHeader[] = '			line-height:125%;';
$LaPostaHeader[] = '			letter-spacing:normal;';
$LaPostaHeader[] = '			text-align:left;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		h4{';
$LaPostaHeader[] = '			color:#202020;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:18px;';
$LaPostaHeader[] = '			font-style:normal;';
$LaPostaHeader[] = '			font-weight:bold;';
$LaPostaHeader[] = '			line-height:125%;';
$LaPostaHeader[] = '			letter-spacing:normal;';
$LaPostaHeader[] = '			text-align:left;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templatePreheader{';
$LaPostaHeader[] = '			background-color:#fafafa;';
$LaPostaHeader[] = '			background-image:none;';
$LaPostaHeader[] = '			background-repeat:no-repeat;';
$LaPostaHeader[] = '			background-position:center;';
$LaPostaHeader[] = '			background-size:cover;';
$LaPostaHeader[] = '			border-top:0;';
$LaPostaHeader[] = '			border-bottom:0;';
$LaPostaHeader[] = '			padding-top:9px;';
$LaPostaHeader[] = '			padding-bottom:9px;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templatePreheader .mcnTextContent,#templatePreheader .mcnTextContent p{';
$LaPostaHeader[] = '			color:#656565;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:12px;';
$LaPostaHeader[] = '			line-height:150%;';
$LaPostaHeader[] = '			text-align:left;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templatePreheader .mcnTextContent a,#templatePreheader .mcnTextContent p a{';
$LaPostaHeader[] = '			color:#656565;';
$LaPostaHeader[] = '			font-weight:normal;';
$LaPostaHeader[] = '			text-decoration:underline;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateHeader{';
$LaPostaHeader[] = '			background-color:#ffffff;';
$LaPostaHeader[] = '			background-image:none;';
$LaPostaHeader[] = '			background-repeat:no-repeat;';
$LaPostaHeader[] = '			background-position:center;';
$LaPostaHeader[] = '			background-size:cover;';
$LaPostaHeader[] = '			border-top:0;';
$LaPostaHeader[] = '			border-bottom:0;';
$LaPostaHeader[] = '			padding-top:9px;';
$LaPostaHeader[] = '			padding-bottom:0;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateHeader .mcnTextContent,#templateHeader .mcnTextContent p{';
$LaPostaHeader[] = '			color:#202020;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:16px;';
$LaPostaHeader[] = '			line-height:150%;';
$LaPostaHeader[] = '			text-align:left;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateHeader .mcnTextContent a,#templateHeader .mcnTextContent p a{';
$LaPostaHeader[] = '			color:#007C89;';
$LaPostaHeader[] = '			font-weight:normal;';
$LaPostaHeader[] = '			text-decoration:underline;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateBody{';
$LaPostaHeader[] = '			background-color:#ffffff;';
$LaPostaHeader[] = '			background-image:none;';
$LaPostaHeader[] = '			background-repeat:no-repeat;';
$LaPostaHeader[] = '			background-position:center;';
$LaPostaHeader[] = '			background-size:cover;';
$LaPostaHeader[] = '			border-top:0;';
$LaPostaHeader[] = '			border-bottom:2px solid #EAEAEA;';
$LaPostaHeader[] = '			padding-top:0;';
$LaPostaHeader[] = '			padding-bottom:9px;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateBody .mcnTextContent,#templateBody .mcnTextContent p{';
$LaPostaHeader[] = '			color:#202020;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:16px;';
$LaPostaHeader[] = '			line-height:150%;';
$LaPostaHeader[] = '			text-align:left;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateBody .mcnTextContent a,#templateBody .mcnTextContent p a{';
$LaPostaHeader[] = '			color:#007C89;';
$LaPostaHeader[] = '			font-weight:normal;';
$LaPostaHeader[] = '			text-decoration:underline;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateFooter{';
$LaPostaHeader[] = '			background-color:#fafafa;';
$LaPostaHeader[] = '			background-image:none;';
$LaPostaHeader[] = '			background-repeat:no-repeat;';
$LaPostaHeader[] = '			background-position:center;';
$LaPostaHeader[] = '			background-size:cover;';
$LaPostaHeader[] = '			border-top:0;';
$LaPostaHeader[] = '			border-bottom:0;';
$LaPostaHeader[] = '			padding-top:9px;';
$LaPostaHeader[] = '			padding-bottom:9px;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateFooter .mcnTextContent,#templateFooter .mcnTextContent p{';
$LaPostaHeader[] = '			color:#656565;';
$LaPostaHeader[] = '			font-family:Helvetica;';
$LaPostaHeader[] = '			font-size:12px;';
$LaPostaHeader[] = '			line-height:150%;';
$LaPostaHeader[] = '			text-align:center;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '		#templateFooter .mcnTextContent a,#templateFooter .mcnTextContent p a{';
$LaPostaHeader[] = '			color:#656565;';
$LaPostaHeader[] = '			font-weight:normal;';
$LaPostaHeader[] = '			text-decoration:underline;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '	@media only screen and (min-width:768px){';
$LaPostaHeader[] = '		.templateContainer{';
$LaPostaHeader[] = '			width:600px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		body,table,td,p,a,li,blockquote{';
$LaPostaHeader[] = '			-webkit-text-size-adjust:none !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		body{';
$LaPostaHeader[] = '			width:100% !important;';
$LaPostaHeader[] = '			min-width:100% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		#bodyCell{';
$LaPostaHeader[] = '			padding-top:10px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnRetinaImage{';
$LaPostaHeader[] = '			max-width:100% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnImage{';
$LaPostaHeader[] = '			width:100% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnCartContainer,.mcnCaptionTopContent,.mcnRecContentContainer,.mcnCaptionBottomContent,.mcnTextContentContainer,.mcnBoxedTextContentContainer,.mcnImageGroupContentContainer,.mcnCaptionLeftTextContentContainer,.mcnCaptionRightTextContentContainer,.mcnCaptionLeftImageContentContainer,.mcnCaptionRightImageContentContainer,.mcnImageCardLeftTextContentContainer,.mcnImageCardRightTextContentContainer,.mcnImageCardLeftImageContentContainer,.mcnImageCardRightImageContentContainer{';
$LaPostaHeader[] = '			max-width:100% !important;';
$LaPostaHeader[] = '			width:100% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnBoxedTextContentContainer{';
$LaPostaHeader[] = '			min-width:100% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnImageGroupContent{';
$LaPostaHeader[] = '			padding:9px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnCaptionLeftContentOuter .mcnTextContent,.mcnCaptionRightContentOuter .mcnTextContent{';
$LaPostaHeader[] = '			padding-top:9px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnImageCardTopImageContent,.mcnCaptionBottomContent:last-child .mcnCaptionBottomImageContent,.mcnCaptionBlockInner .mcnCaptionTopContent:last-child .mcnTextContent{';
$LaPostaHeader[] = '			padding-top:18px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnImageCardBottomImageContent{';
$LaPostaHeader[] = '			padding-bottom:9px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnImageGroupBlockInner{';
$LaPostaHeader[] = '			padding-top:0 !important;';
$LaPostaHeader[] = '			padding-bottom:0 !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnImageGroupBlockOuter{';
$LaPostaHeader[] = '			padding-top:9px !important;';
$LaPostaHeader[] = '			padding-bottom:9px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnTextContent,.mcnBoxedTextContentColumn{';
$LaPostaHeader[] = '			padding-right:18px !important;';
$LaPostaHeader[] = '			padding-left:18px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnImageCardLeftImageContent,.mcnImageCardRightImageContent{';
$LaPostaHeader[] = '			padding-right:18px !important;';
$LaPostaHeader[] = '			padding-bottom:0 !important;';
$LaPostaHeader[] = '			padding-left:18px !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcpreview-image-uploader{';
$LaPostaHeader[] = '			display:none !important;';
$LaPostaHeader[] = '			width:100% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		h1{';
$LaPostaHeader[] = '			font-size:22px !important;';
$LaPostaHeader[] = '			line-height:125% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		h2{';
$LaPostaHeader[] = '			font-size:20px !important;';
$LaPostaHeader[] = '			line-height:125% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		h3{';
$LaPostaHeader[] = '			font-size:18px !important;';
$LaPostaHeader[] = '			line-height:125% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		h4{';
$LaPostaHeader[] = '			font-size:16px !important;';
$LaPostaHeader[] = '			line-height:150% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		.mcnBoxedTextContentContainer .mcnTextContent,.mcnBoxedTextContentContainer .mcnTextContent p{';
$LaPostaHeader[] = '			font-size:14px !important;';
$LaPostaHeader[] = '			line-height:150% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		#templatePreheader{';
$LaPostaHeader[] = '			display:block !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		#templatePreheader .mcnTextContent,#templatePreheader .mcnTextContent p{';
$LaPostaHeader[] = '			font-size:14px !important;';
$LaPostaHeader[] = '			line-height:150% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		#templateHeader .mcnTextContent,#templateHeader .mcnTextContent p{';
$LaPostaHeader[] = '			font-size:16px !important;';
$LaPostaHeader[] = '			line-height:150% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		#templateBody .mcnTextContent,#templateBody .mcnTextContent p{';
$LaPostaHeader[] = '			font-size:16px !important;';
$LaPostaHeader[] = '			line-height:150% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}	@media only screen and (max-width: 480px){';
$LaPostaHeader[] = '		#templateFooter .mcnTextContent,#templateFooter .mcnTextContent p{';
$LaPostaHeader[] = '			font-size:14px !important;';
$LaPostaHeader[] = '			line-height:150% !important;';
$LaPostaHeader[] = '		}';
$LaPostaHeader[] = '';
$LaPostaHeader[] = '}</style></head>';
$LaPostaHeader[] = '    <body style="height: 100%;margin: 0;padding: 0;width: 100%;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #fafafa;">';
$LaPostaHeader[] = '        <!--*|IF:MC_PREVIEW_TEXT|*-->';
$LaPostaHeader[] = '        <!--[if !gte mso 9]><!----><span class="mcnPreviewText" style="display:none; font-size:0px; line-height:0px; max-height:0px; max-width:0px; opacity:0; overflow:hidden; visibility:hidden; mso-hide:all;">[[PREVIEW]]</span><!--<![endif]-->';
$LaPostaHeader[] = '        <!--*|END:IF|*-->';
$LaPostaHeader[] = '        <center>';
$LaPostaHeader[] = '            <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" id="bodyTable" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;height: 100%;margin: 0;padding: 0;width: 100%;background-color: #fafafa;">';
$LaPostaHeader[] = '                <tr>';
$LaPostaHeader[] = '                    <td align="center" valign="top" id="bodyCell" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;height: 100%;margin: 0;padding: 10px;width: 100%;border-top: 0;">';
$LaPostaHeader[] = '                        <!-- BEGIN TEMPLATE // -->';
$LaPostaHeader[] = '                        <!--[if (gte mso 9)|(IE)]>';
$LaPostaHeader[] = '                        <table align="center" border="0" cellspacing="0" cellpadding="0" width="600" style="width:600px;">';
$LaPostaHeader[] = '                        <tr>';
$LaPostaHeader[] = '                        <td align="center" valign="top" width="600" style="width:600px;">';
$LaPostaHeader[] = '                        <![endif]-->';
$LaPostaHeader[] = '                        <table border="0" cellpadding="0" cellspacing="0" width="100%" class="templateContainer" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;border: 0;max-width: 600px !important;">';

#PREHEADER
if(isset($preheader) AND $preheader != '') {
	$LaPostaHeader[] = '                            <tr>';
	$LaPostaHeader[] = '                                <td valign="top" id="templatePreheader" style="background:#fafafa none no-repeat center/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #fafafa;background-image: none;background-repeat: no-repeat;background-position: center;background-size: cover;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 9px;"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaHeader[] = '    <tbody class="mcnTextBlockOuter">';
	$LaPostaHeader[] = '        <tr>';
	$LaPostaHeader[] = '            <td valign="top" class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaHeader[] = '              	<!--[if mso]>';
	$LaPostaHeader[] = '				<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
	$LaPostaHeader[] = '				<tr>';
	$LaPostaHeader[] = '				<![endif]-->';
	$LaPostaHeader[] = '								';
	$LaPostaHeader[] = '			    ';
	$LaPostaHeader[] = '				<!--[if mso]>';
	$LaPostaHeader[] = '				<td valign="top" width="600" style="width:600px;">';
	$LaPostaHeader[] = '				<![endif]-->';
	$LaPostaHeader[] = '				';
	$LaPostaHeader[] = '                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">';
	$LaPostaHeader[] = '                    <tbody><tr>';
	$LaPostaHeader[] = '                        ';
	$LaPostaHeader[] = '                        <td valign="top" class="mcnTextContent" style="padding: 0px 18px 9px;text-align: center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #656565;font-family: Helvetica;font-size: 12px;line-height: 150%;">';
	$LaPostaHeader[] = $preheader;
	$LaPostaHeader[] = '                            ';
	$LaPostaHeader[] = '                        </td>';
	$LaPostaHeader[] = '                    </tr>';
	$LaPostaHeader[] = '                </tbody></table>';
	$LaPostaHeader[] = '                ';
	$LaPostaHeader[] = '                ';
	$LaPostaHeader[] = '				<!--[if mso]>';
	$LaPostaHeader[] = '				</td>';
	$LaPostaHeader[] = '				<![endif]-->';
	$LaPostaHeader[] = '                ';
	$LaPostaHeader[] = '				<!--[if mso]>';
	$LaPostaHeader[] = '				</tr>';
	$LaPostaHeader[] = '				</table>';
	$LaPostaHeader[] = '				<![endif]-->';
	$LaPostaHeader[] = '            </td>';
	$LaPostaHeader[] = '        </tr>';
	$LaPostaHeader[] = '    </tbody>';
	$LaPostaHeader[] = '</table></td>';
	$LaPostaHeader[] = '                            </tr>';
}

#HEADER
$LaPostaHeader[] = '                            <tr>';
$LaPostaHeader[] = '                                <td valign="top" id="templateHeader" style="background:#ffffff none no-repeat center/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #ffffff;background-image: none;background-repeat: no-repeat;background-position: center;background-size: cover;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 0;"><table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnImageBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '    <tbody class="mcnImageBlockOuter">';
$LaPostaHeader[] = '            <tr>';
$LaPostaHeader[] = '                <td valign="top" style="padding: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnImageBlockInner">';
$LaPostaHeader[] = '                    <table align="left" width="100%" border="0" cellpadding="0" cellspacing="0" class="mcnImageContentContainer" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '                        <tbody><tr>';
$LaPostaHeader[] = '                            <td class="mcnImageContent" valign="top" style="padding-right: 9px;padding-left: 9px;padding-top: 0;padding-bottom: 0;text-align: center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '                                ';
$LaPostaHeader[] = '                                    ';
$LaPostaHeader[] = '                                        <img align="center" alt="" src="https://gallery.mailchimp.com/c2563bff0a72ae50bcc31afeb/images/77ad485a-4021-4815-a3c9-b3754aa50ad0.png" width="564" lp-max-width="1032" class="mcnImage">';
$LaPostaHeader[] = '                                    ';
$LaPostaHeader[] = '                                ';
$LaPostaHeader[] = '                            </td>';
$LaPostaHeader[] = '                        </tr>';
$LaPostaHeader[] = '                    </tbody></table>';
$LaPostaHeader[] = '                </td>';
$LaPostaHeader[] = '            </tr>';
$LaPostaHeader[] = '    </tbody>';
$LaPostaHeader[] = '</table></td>';
$LaPostaHeader[] = '                            </tr>';

#BERICHT
$LaPostaHeader[] = '                            <tr>';
$LaPostaHeader[] = '                                <td valign="top" id="templateBody" style="background:#ffffff none no-repeat center/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #ffffff;background-image: none;background-repeat: no-repeat;background-position: center;background-size: cover;border-top: 0;border-bottom: '.(((isset($disclaimer) AND $disclaimer != '') OR (isset($afmelding) AND $afmelding != '')) ? 2 : 0).'px solid #EAEAEA;padding-top: 0;padding-bottom: 9px;">';
$LaPostaHeader[] = '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnDividerBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;table-layout: fixed !important;">';
$LaPostaHeader[] = '    <tbody class="mcnDividerBlockOuter">';
$LaPostaHeader[] = '        <tr>';
$LaPostaHeader[] = '            <td class="mcnDividerBlockInner" style="min-width: 100%;padding: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '                <table class="mcnDividerContent" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width: 100%;border-top: 2px solid #EAEAEA;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '                    <tbody><tr>';
$LaPostaHeader[] = '                        <td style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '                            <span></span>';
$LaPostaHeader[] = '                        </td>';
$LaPostaHeader[] = '                    </tr>';
$LaPostaHeader[] = '                </tbody></table>';
$LaPostaHeader[] = '<!--            ';
$LaPostaHeader[] = '                <td class="mcnDividerBlockInner" style="padding: 18px;">';
$LaPostaHeader[] = '                <hr class="mcnDividerContent" style="border-bottom-color:none; border-left-color:none; border-right-color:none; border-bottom-width:0; border-left-width:0; border-right-width:0; margin-top:0; margin-right:0; margin-bottom:0; margin-left:0;" />';
$LaPostaHeader[] = '-->';
$LaPostaHeader[] = '            </td>';
$LaPostaHeader[] = '        </tr>';
$LaPostaHeader[] = '    </tbody>';
$LaPostaHeader[] = '</table>';
$LaPostaHeader[] = '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '    <tbody class="mcnTextBlockOuter">';
$LaPostaHeader[] = '        <tr>';
$LaPostaHeader[] = '            <td valign="top" class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
$LaPostaHeader[] = '              	<!--[if mso]>';
$LaPostaHeader[] = '				<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
$LaPostaHeader[] = '				<tr>';
$LaPostaHeader[] = '				<![endif]-->';
$LaPostaHeader[] = '			    ';
$LaPostaHeader[] = '				<!--[if mso]>';
$LaPostaHeader[] = '				<td valign="top" width="600" style="width:600px;">';
$LaPostaHeader[] = '				<![endif]-->';
$LaPostaHeader[] = '                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">';
$LaPostaHeader[] = '                    <tbody><tr>';
$LaPostaHeader[] = '                        ';
$LaPostaHeader[] = '                        <td valign="top" class="mcnTextContent" style="padding-top: 0;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #202020;font-family: Helvetica;font-size: 16px;line-height: 150%;text-align: left;">';



$LaPostaFooter[] = '                        </td>';
$LaPostaFooter[] = '                    </tr>';
$LaPostaFooter[] = '                </tbody></table>';
$LaPostaFooter[] = '				<!--[if mso]>';
$LaPostaFooter[] = '				</td>';
$LaPostaFooter[] = '				<![endif]-->';
$LaPostaFooter[] = '                ';
$LaPostaFooter[] = '				<!--[if mso]>';
$LaPostaFooter[] = '				</tr>';
$LaPostaFooter[] = '				</table>';
$LaPostaFooter[] = '				<![endif]-->';
$LaPostaFooter[] = '            </td>';
$LaPostaFooter[] = '        </tr>';
$LaPostaFooter[] = '    </tbody>';
$LaPostaFooter[] = '</table>';
$LaPostaFooter[] = '</td>';
$LaPostaFooter[] = '                            </tr>';
$LaPostaFooter[] = '                            <tr>';
$LaPostaFooter[] = '                                <td valign="top" id="templateFooter" style="background:#fafafa none no-repeat center/cover;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;background-color: #fafafa;background-image: none;background-repeat: no-repeat;background-position: center;background-size: cover;border-top: 0;border-bottom: 0;padding-top: 9px;padding-bottom: 9px;">';

#DISCLAIMER
if(isset($disclaimer) AND $disclaimer != '') {
	$LaPostaFooter[] = '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaFooter[] = '    <tbody class="mcnTextBlockOuter">';
	$LaPostaFooter[] = '        <tr>';
	$LaPostaFooter[] = '            <td valign="top" class="mcnTextBlockInner" style="padding-top: 9px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaFooter[] = '              	<!--[if mso]>';
	$LaPostaFooter[] = '				<table align="left" border="0" cellspacing="0" cellpadding="0" width="100%" style="width:100%;">';
	$LaPostaFooter[] = '				<tr>';
	$LaPostaFooter[] = '				<![endif]-->';
	$LaPostaFooter[] = '			    ';
	$LaPostaFooter[] = '				<!--[if mso]>';
	$LaPostaFooter[] = '				<td valign="top" width="600" style="width:600px;">';
	$LaPostaFooter[] = '				<![endif]-->';
	$LaPostaFooter[] = '                <table align="left" border="0" cellpadding="0" cellspacing="0" style="max-width: 100%;min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" width="100%" class="mcnTextContentContainer">';
	$LaPostaFooter[] = '                    <tbody><tr>';
	$LaPostaFooter[] = '                        ';
	$LaPostaFooter[] = '                        <td valign="top" class="mcnTextContent" style="padding-top: 0;padding-right: 18px;padding-bottom: 9px;padding-left: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;color: #656565;font-family: Helvetica;font-size: 12px;line-height: 150%;text-align: center;">';
	$LaPostaFooter[] = '                        ';
	$LaPostaFooter[] = '                            <span style="font-size:12px"><em>'. $disclaimer .'</em></span>';
	$LaPostaFooter[] = '                        </td>';
	$LaPostaFooter[] = '                    </tr>';
	$LaPostaFooter[] = '                </tbody></table>';
	$LaPostaFooter[] = '				<!--[if mso]>';
	$LaPostaFooter[] = '				</td>';
	$LaPostaFooter[] = '				<![endif]-->';
	$LaPostaFooter[] = '                ';
	$LaPostaFooter[] = '				<!--[if mso]>';
	$LaPostaFooter[] = '				</tr>';
	$LaPostaFooter[] = '				</table>';
	$LaPostaFooter[] = '				<![endif]-->';
	$LaPostaFooter[] = '            </td>';
	$LaPostaFooter[] = '        </tr>';
	$LaPostaFooter[] = '    </tbody>';
	$LaPostaFooter[] = '</table>';
}

#AFMELDBLOK
if(isset($afmelding) AND $afmelding != '') {
	$LaPostaFooter[] = '<table border="0" cellpadding="0" cellspacing="0" width="100%" class="mcnBoxedTextBlock" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaFooter[] = '    <!--[if gte mso 9]>';
	$LaPostaFooter[] = '	<table align="center" border="0" cellspacing="0" cellpadding="0" width="100%">';
	$LaPostaFooter[] = '	<![endif]-->';
	$LaPostaFooter[] = '	<tbody class="mcnBoxedTextBlockOuter">';
	$LaPostaFooter[] = '        <tr>';
	$LaPostaFooter[] = '            <td valign="top" class="mcnBoxedTextBlockInner" style="mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaFooter[] = '                ';
	$LaPostaFooter[] = '				<!--[if gte mso 9]>';
	$LaPostaFooter[] = '				<td align="center" valign="top" ">';
	$LaPostaFooter[] = '				<![endif]-->';
	$LaPostaFooter[] = '                <table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;" class="mcnBoxedTextContentContainer">';
	$LaPostaFooter[] = '                    <tbody><tr>';
	$LaPostaFooter[] = '                        ';
	$LaPostaFooter[] = '                        <td style="padding-top: 9px;padding-left: 18px;padding-bottom: 9px;padding-right: 18px;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaFooter[] = '                        ';
	$LaPostaFooter[] = '                            <table border="0" cellspacing="0" class="mcnTextContentContainer" width="100%" style="min-width: 100% !important;background-color: #FAFAFA;border: 1px dashed #8C1974;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;">';
	$LaPostaFooter[] = '                                <tbody><tr>';
	$LaPostaFooter[] = '                                    <td valign="top" class="mcnTextContent" style="padding: 18px;color: #202020;font-family: Helvetica;font-size: 12px;font-weight: normal;text-align: center;mso-line-height-rule: exactly;-ms-text-size-adjust: 100%;-webkit-text-size-adjust: 100%;word-break: break-word;line-height: 150%;">';
	$LaPostaFooter[] = $afmelding;                                    	
	$LaPostaFooter[] = '                                    </td>';
	$LaPostaFooter[] = '                                </tr>';
	$LaPostaFooter[] = '                            </tbody></table>';
	$LaPostaFooter[] = '                        </td>';
	$LaPostaFooter[] = '                    </tr>';
	$LaPostaFooter[] = '                </tbody></table>';
	$LaPostaFooter[] = '				<!--[if gte mso 9]>';
	$LaPostaFooter[] = '				</td>';
	$LaPostaFooter[] = '				<![endif]-->';
	$LaPostaFooter[] = '                ';
	$LaPostaFooter[] = '				<!--[if gte mso 9]>';
	$LaPostaFooter[] = '                </tr>';
	$LaPostaFooter[] = '                </table>';
	$LaPostaFooter[] = '				<![endif]-->';
	$LaPostaFooter[] = '            </td>';
	$LaPostaFooter[] = '        </tr>';
	$LaPostaFooter[] = '    </tbody>';
	$LaPostaFooter[] = '</table>';
}

#FOOTER
$LaPostaFooter[] = '</td>';
$LaPostaFooter[] = '                            </tr>';
$LaPostaFooter[] = '                        </table>';
$LaPostaFooter[] = '                        <!--[if (gte mso 9)|(IE)]>';
$LaPostaFooter[] = '                        </td>';
$LaPostaFooter[] = '                        </tr>';
$LaPostaFooter[] = '                        </table>';
$LaPostaFooter[] = '                        <![endif]-->';
$LaPostaFooter[] = '                        <!-- // END TEMPLATE -->';
$LaPostaFooter[] = '                    </td>';
$LaPostaFooter[] = '                </tr>';
$LaPostaFooter[] = '            </table>';
$LaPostaFooter[] = '        </center>';
$LaPostaFooter[] = '                <center>';
$LaPostaFooter[] = '                <style type="text/css">';
$LaPostaFooter[] = '                    @media only screen and (max-width: 480px){';
$LaPostaFooter[] = '                        table#canspamBar td{font-size:14px !important;}';
$LaPostaFooter[] = '                        table#canspamBar td a{display:block !important; margin-top:10px !important;}';
$LaPostaFooter[] = '                    }';
$LaPostaFooter[] = '                </style>';
$LaPostaFooter[] = '            </center></body>';
$LaPostaFooter[] = '</html>';

?>