on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy to FTP
    runs-on: ubuntu-latest
    steps:
    - name: Update version
      uses: DamianReeves/write-file-action@master
      with:
        path: version.txt
        contents: |
          1
        write-mode: overwrite      

    - name: 🚚 Get latest code
      uses: actions/checkout@v6        

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ${{ secrets.new_ftp_server }}
        username: ${{ secrets.new_ftp_username }}
        password: ${{ secrets.new_ftp_password }}
        server-dir: ${{ secrets.new_ftp_userdir }}
        exclude: |
          **/.git*
          **/.git*/**
          **/Classes/KKDConfig.php
          **/docs/**
